const mongoose = require("mongoose");

const transactionSchema = new mongoose.Schema({
        fromAccount:{
                type:mongoose.Schema.Types.ObjectId,
                ref:"account",
                required:[true,"From account is required for creating a transaction"],
                index:true  //to make search faster on this field
        },

        toAccount:{
            type:mongoose.Schema.Types.ObjectId,
            ref:"account",
            required:[true,"To account is required for creating a transaction"],
            index:true  //to make search faster on this field
        },
        status:{
            type:String,
            enum:{
                values:["PENDING", "COMPLETED", "FAILED", "REVERSED"],
                message:"Status should be either PENDING, COMPLETED ,FAILED or REVERSED"
            },
            default:"PENDING"
        },
        amount:{
            type:Number,
            required:[true,"Amount is required for creating a transaction"],
            min:[0,"Amount  cannot be negative "]
         },
         // this is to track the transaction and to make sure that the transaction is not processed multiple times in case of network failure or any other reason
         // this is to make sure that the transaction is idempotent and if the same transaction is sent multiple times, it will be processed only once
         //this is generated by the client and sent to the server along with the transaction request and server will check if the idempotency key is already present in the database, if yes then it will not process the transaction again and will return the previous response
         idempotencyKey:{
            type:String,
            required:[true,"Idempotency key is required for creating a transaction"],
            index:true,  //to make search faster on this field
            unique:true
         }
},
    {
        timestamps:true
    }
)
   

const transactionModel = mongoose.model("transaction",transactionSchema);

module.exports = transactionModel;